/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.silasvb.refactoring;

public abstract class Movie {

  private static class ChildrensMovie extends Movie {
    private ChildrensMovie(String title) {
      super(title, CHILDRENS);
    }
  }

  private static class RegularMovie extends Movie {
    private RegularMovie(String title) {
      super(title, REGULAR);
    }
  }

  private static class NewRelease extends Movie {
    private NewRelease(String title) {
      super(title, NEW_RELEASE);
    }
  }

  public static final int CHILDRENS = 2;
  public static final int REGULAR = 0;
  public static final int NEW_RELEASE = 1;

  private String title;
  private int priceCode;

  public static Movie createMovie(String title, int priceCode) {
    if (priceCode == CHILDRENS) {
      return new ChildrensMovie(title);
    }
    if (priceCode == REGULAR) {
      return new RegularMovie(title);
    }

    if (priceCode == NEW_RELEASE) {
      return new NewRelease(title);
    }

    return null;
  }

  private Movie(String title, int priceCode) {
    this.title = title;
    this.priceCode = priceCode;
  }

  public String getTitle() {
    return title;
  }

  public int getPiceCode() {
    return priceCode;
  }

  public double getCharge(int daysRented) {
    double result = 0;
    switch (getPiceCode()) {
      case Movie.REGULAR:
        result += 2;
        if (daysRented > 2) {
          result += (daysRented - 2) * 1.5;
        }
        break;
      case Movie.NEW_RELEASE:
        result += daysRented * 3;
        break;

      case Movie.CHILDRENS:
        result += 1.5;
        if (daysRented > 3) {
          result += (daysRented - 3) * 1.5;
        }
        break;
    }
    return result;
  }

  public int getFrequentRenterPoints(int duration) {
    int frequentRenterPoints = 1;

    if (getPiceCode() == Movie.NEW_RELEASE && duration > 1) {
      frequentRenterPoints++;
    }
    return frequentRenterPoints;
  }
}
