/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.silasvb.refactoring;

import org.silasvb.refactoring.price.Price;
import org.silasvb.refactoring.renterpoints.RenterPoints;

public abstract class Movie {

  private final String title;

  private final Price price;
  private final RenterPoints renterPoints;

  protected Movie(String title, Price price, RenterPoints renterPoints) {
    this.title = title;
    this.price = price;
    this.renterPoints = renterPoints;
  }

  public String getTitle() {
    return title;
  }

  public double getCharge(int daysRented) {
    return price.getCharge(daysRented);
  }

  public int getFrequentRenterPoints(int duration) {
    return renterPoints.getRenterPoints(duration);
  }
}
